hydra:
  job:
    chdir: true
  run:
    dir: outputs/${name}/${my_override_dirname:${hydra.overrides}}
  sweep:
    dir: multirun/${name}
    subdir: ${my_override_dirname:${hydra.overrides}}
  sweeper:
    params:
      lr_D:     2e-8,2e-7,2e-6,2e-5,2e-4,2e-3
      lr_G:     2e-6,2e-5,2e-4,2e-3,2e-2,2e-1

defaults:
  - base
  - model:          cycle_gan
  - visualizer:     [mlflow]
  - train_defaults
  - _self_

dataroot:         'datasets/oyu_stone_dataset'
name:             'oyu_cyclegan_test_run_11'
load_size:        2078
crop_size:        2048
netG:             'unet_2048'
init_type:        'kaiming'
no_dropout:       true
gpu_ids:          '3'

suffix:           'lr_D-{lr_D}-lr_G-{lr_G}'
seed:             42
