hydra:
  job:
    chdir: true
  run:
    dir: outputs/${name}/${my_override_dirname:${hydra.overrides}}
  sweep:
    dir: multirun/${name}
    subdir: ${my_override_dirname:${hydra.overrides}}

defaults:
  - base
  - model:          cycle_gan
  - visualizer:     [mlflow]
  - train_defaults
  - _self_

dataroot:         'datasets/data'
dataset_mode:     'multifile'
name:             'multifiles_test_run'
load_size:        2078
crop_size:        2048
netG:             'unet_2048'
init_type:        'kaiming'
no_dropout:       true


suffix:           'lr_D-{lr_D}-lr_G-{lr_G}'
seed:             42
