hydra:
  job:
    chdir: true
  run:
    dir: outputs/${name}/${my_override_dirname:${hydra.overrides}}
  sweep:
    dir: multirun/${name}
    subdir: ${my_override_dirname:${hydra.overrides}}
  sweeper:
    params:
      lr_D:     2e-8,2e-7,2e-6,2e-5,2e-4,2e-3
      lr_G:     2e-6,2e-5,2e-4,2e-3,2e-2,2e-1

defaults:
  - base
  - model:          cycle_gan
  - visualizer:     [mlflow]
  - train_defaults
  - _self_

dataroot:         'datasets/colbase_multifile_dataset_4096x2048'
dataset_mode:     'multifile'
name:             'colbase_multifiles_run_01'
load_size:        2078
crop_size:        2048
netG:             'unet_2048'
init_type:        'kaiming'
no_dropout:       true
gan_mode:         'lsgan'
lambda_identity:  0.0
save_latest_freq: 10000
save_epoch_freq:  50
display_freq:     820
update_html_freq: 1640
gpu_ids:          '3'
color_spaces:
  - "lds"
  - "ybk"

suffix:           'lr_D-{lr_D}-lr_G-{lr_G}'
seed:             42
