hydra:
  job:
    chdir: true
  run:
    dir: /raid/itagaki/oyu/outputs/${name}/${my_override_dirname:${hydra.overrides}}
  sweep:
    dir: /raid/itagaki/oyu/multirun/${name}
    subdir: ${my_override_dirname:${hydra.overrides}}
  sweeper:
    params:
      lr_D:     2e-5,6.32e-5,2e-4,6.32e-4,2e-3
      lr_G:     2e-4,6.32e-4,2e-3,6.32e-3,2e-2

defaults:
  - base
  - model:          masked_cycle_gan
  - visualizer:     [mlflow]
  - train_defaults
  - _self_

dataroot:         'datasets/masked_stone_dataset'
dataset_mode:     'masked'
name:             'oyu_masked_cyclegan_run_05'
tracking_uri:     'file:/raid/itagaki/mlruns'
registry_uri:     'file:/raid/itagaki/mlruns'
load_size:        2078
crop_size:        2048
netG:             'unet_2048'
netD:             'n_layers'
n_layers_D:       8
init_type:        'kaiming'
gan_mode:         'lsgan'
no_dropout:       true
gpu_ids:          '3'
n_epochs:         100
n_epochs_decay:   300
save_latest_freq: 10000
save_epoch_freq:  50
display_freq:     1000
update_html_freq: 2000

suffix:           'lr_D-{lr_D}-lr_G-{lr_G}'
seed:             42
