hydra:
  job:
    chdir: true
  run:
    dir: /raid/itagaki/colbase_cyclegan/outputs/${name}/${my_override_dirname:${hydra.overrides}}
  sweep:
    dir: /raid/itagaki/colbase_cyclegan/multirun/${name}
    subdir: ${my_override_dirname:${hydra.overrides}}
  sweeper:
    params:
      lr_D:     1e-4,2e-4,3e-4,4e-4
      lr_G:     1e-3,2e-3,3e-3

defaults:
  - base
  - model:          cycle_gan
  - visualizer:     [mlflow]
  - train_defaults
  - _self_

dataroot:         'datasets/colbase_multifile_dataset_4096x2048'
dataset_mode:     'multifile'
name:             'colbase_multifiles_run_08'
tracking_uri:     'file:/raid/itagaki/mlruns'
registry_uri:     'file:/raid/itagaki/mlruns'
load_size:        2078
crop_size:        2048
netG:             'unet_2048'
netD:             'n_layers'
n_layers_D:       4
init_type:        'kaiming'
no_dropout:       true
gan_mode:         'lsgan'
lambda_A: 20.0
lambda_B: 20.0
lambda_identity:  0.0
save_latest_freq: 10000
save_epoch_freq:  50
display_freq:     820
update_html_freq: 1640
gpu_ids:          '3'
color_spaces:
  - "lds"
  - "ybk"

suffix:           'lr_D-{lr_D}-lr_G-{lr_G}'
seed:             42
