hydra:
  job:
    chdir: true
  run:
    dir: outputs/${name}/${my_override_dirname:${hydra.overrides}}
  sweep:
    dir: multirun/${name}
    subdir: ${my_override_dirname:${hydra.overrides}}
  sweeper:
    params:
      lr_D:     2e-7,5e-7,1e-6,1.5e-6,2e-6
      lr_G:     2e-4,5e-4,1e-3,1.5e-3,2e-3
defaults:
  - base
  - model:          cycle_gan
  - visualizer:     [mlflow]
  - train_defaults
  - _self_

dataroot:         'datasets/colbase_dataset'
name:             'colbase_cyclegan_exp_1'
load_size:        2078
crop_size:        2048
netG:             'unet_2048'
init_type:        'kaiming'
no_dropout:       true
gan_mode:         'vanilla'
save_latest_freq: 10000
save_epoch_freq:  50
display_freq:     820
update_html_freq: 1640
gpu_ids:          '3'

suffix:           'lr_D-{lr_D}-lr_G-{lr_G}'
seed:             42